apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: happy-donut
resources:
  - ventas.yaml
  - inventario.yaml
  - usuarios.yaml
  - finanzas.yaml
  - tienda-virtual.yaml
  - config.yaml
  - network-policy.yaml
