apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hexagonal-api
  template:
    metadata:
      labels:
        app: hexagonal-api
    spec:
      containers:
      - name: adapter-rest
        image: royfrankly/happydonnut-app-usuarios:v1
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: hexagonal-config