apiVersion: v1
kind: ConfigMap
metadata: {name: happy-donut-config}
data:
  APP_ENV: local
  APP_DEBUG: "false"
  CACHE_STORE: file
  REDIS_HOST: redis
  OTEL_PHP_AUTOLOAD_ENABLED: "true"
  OTEL_TRACES_EXPORTER: otlp
  OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
  OTEL_EXPORTER_OTLP_ENDPOINT: http://happy-donut-otel-collector.observability.svc.cluster.local:4318
  OTEL_PROPAGATORS: tracecontext,baggage
  OTEL_LOG_LEVEL: info
