apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: happy-donut
resources:
  - ../../base
  - namespace.yaml
  - data-plane.yaml
patches:
  - path: local-patches.yaml
  - path: config-patch.yaml
images:
  - {name: ghcr.io/happy-donut-software/happy-donnut-software/ventas, newName: happy-donut/ventas, newTag: local}
  - {name: ghcr.io/happy-donut-software/happy-donnut-software/inventario, newName: happy-donut/inventario, newTag: local}
  - {name: ghcr.io/happy-donut-software/happy-donnut-software/usuarios, newName: happy-donut/usuarios, newTag: local}
  - {name: ghcr.io/happy-donut-software/happy-donnut-software/finanzas, newName: happy-donut/finanzas, newTag: local}
  - {name: ghcr.io/happy-donut-software/happy-donnut-software/tienda-virtual, newName: happy-donut/tienda-virtual, newTag: local}