apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: {name: happy-donut-servicios, namespace: happy-donut, labels: {release: prometheus}}
spec:
  namespaceSelector: {matchNames: [happy-donut]}
  selector: {matchLabels: {app.kubernetes.io/part-of: happy-donut}}
  endpoints:
    - {port: http, path: /api/metrics, interval: 15s, scrapeTimeout: 10s}